### ISSUE TITLE
train lora cuda out of memory

### ISSUE THREAD

**Issue by Mrdownshifter** [aigc-apps/sd-webui-EasyPhoto#23]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/57163363/60f68323-b2cd-4ddf-9a72-73471341cdca)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/57163363/b4076bd2-cb3e-490d-b6cf-22d5663ce3f8)
小白一枚，请问大佬，目前使用v100 16g 两张卡训练lora的时候爆出内存溢出，请问可以使用多gpu运行吗？还是有什么其他方法，求帮助。

**Comment by wuziheng** [comment]
不好意思16G 确实当前不可能跑不起来，我个人的测试机器是22g，训练稳态的GPU memory 是小于16G的，我们会尽快优化一下。请关注这个ISSUE，当我们优化完会迅速发布并关联这个ISSUE

**Comment by bubbliiiing** [comment]
我这边测试过3060 12G，可以正常开始，请问你能否指定一张空闲的显卡作为启动显卡？

**Comment by wuziheng** [comment]
export CUDA_VISIBLE_DEVICES=1 限定一下？

**Comment by Mrdownshifter** [comment]
> export CUDA_VISIBLE_DEVICES=1 限定一下？

还是内存溢出，感觉v100 16G 不够

**Comment by bubbliiiing** [comment]
> > export CUDA_VISIBLE_DEVICES=1 限定一下？
> 
> 还是内存溢出，感觉v100 16G 不够

v100应该是足够的，我在3060 12G上做过多次测试，能否麻烦你展示一下在V100上的显存变化以及你的环境信息？

**Comment by Mrdownshifter** [comment]
@bubbliiiing 

https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/57163363/0e1625cc-137a-44a2-9617-ad99372dd009

python3.9 
PyTorch version: 1.12.1+cu113
TensorFlow version: 2.13.0
CUDA Version: 11.3

**Comment by bubbliiiing** [comment]
不好意思，我分析了一下，我看视频中卡1本来就已经用了近8g的显存，这是为什么呢？

**Comment by Mrdownshifter** [comment]
@bubbliiiing 这是已经跑您的项目了，一直再在跑，并不是其他项目占用。

**Comment by bubbliiiing** [comment]
> @bubbliiiing 这是已经跑您的项目了，一直再在跑，并不是其他项目占用。

不好意思，没有及时回复。

正常启动webui无需这么大的显存，请问可以找一张空卡，仅仅启动webui，然后截图看看具体的显存占用吗？
