### ISSUE TITLE
40G,A100显存不够,webui的界面上传图片,默认参数启动,显存不够

### ISSUE THREAD

**Issue by wangxshuai** [aigc-apps/sd-webui-EasyPhoto#31]
Exception in thread Thread-6 (preprocess_images):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/data/weiui/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/preprocess.py", line 125, in preprocess_images
    sub_image = Image.fromarray(cv2.cvtColor(portrait_enhancement(sub_image)[OutputKeys.OUTPUT_IMG], cv2.COLOR_BGR2RGB))
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 219, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 247, in _process_single
    out = self.preprocess(input, **preprocess_params)
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/pipelines/cv/image_portrait_enhancement_pipeline.py", line 178, in preprocess
    img_sr = self.sr_process(img)
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/pipelines/cv/image_portrait_enhancement_pipeline.py", line 161, in sr_process
    output = self.sr_model(img)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/modelscope/models/cv/super_resolution/rrdbnet_arch.py", line 129, in forward
    self.conv_up2(F.interpolate(feat, scale_factor=2, mode='nearest')))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/data/weiui/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 376, in network_Conv2d_forward
    return torch.nn.Conv2d_forward_before_network(self, input)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.73 GiB (GPU 0; 39.42 GiB total capacity; 23.85 GiB already allocated; 12.58 GiB free; 26.15 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

40G,A100显存不够,webui的界面上传图片,默认参数启动,显存不够

**Comment by bubbliiiing** [comment]
Hi，麻烦看一下这个issue https://github.com/aigc-apps/sd-webui-EasyPhoto/issues/30
临时解决方案是删除下个文件的这三行即可
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/main/scripts/preprocess.py
123行开始。
```python
# 根据质量得分、图像大小去判断哪些图片进行codeformer
if (selected_scores[index] < 0.60 or np.shape(sub_image)[0] < 512 or np.shape(sub_image)[1] < 512) and codeformer_num < max_codeformer_num:
    sub_image = Image.fromarray(cv2.cvtColor(portrait_enhancement(sub_image)[OutputKeys.OUTPUT_IMG], cv2.COLOR_BGR2RGB))
    codeformer_num += 1

```

**Comment by wangxshuai** [comment]
> Hi，麻烦看一下这个issue #30 临时解决方案是删除下个文件的这三行即可 https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/main/scripts/preprocess.py 123行开始。
> 
> ```python
> # 根据质量得分、图像大小去判断哪些图片进行codeformer
> if (selected_scores[index] < 0.60 or np.shape(sub_image)[0] < 512 or np.shape(sub_image)[1] < 512) and codeformer_num < max_codeformer_num:
>     sub_image = Image.fromarray(cv2.cvtColor(portrait_enhancement(sub_image)[OutputKeys.OUTPUT_IMG], cv2.COLOR_BGR2RGB))
>     codeformer_num += 1
> ```

可行,我的原始图片确实存在很多比较大的分辨率,注释掉这些的确可以正常训练lora

**Comment by wuziheng** [comment]
@wangxshuai  最新的PR20 已经修复了这一问题，还烦请可以拉下最新分支再做尝试，如果没有问题或者回复，我们会在24小时候关闭该ISSUE
